[package]
name = "fingertips"
version = "0.1.0"
edition = "2021"

[dependencies]
xml-rs = "0.8.20"
rust-stemmers = "^1.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
walkdir = "2.5.0"
